theme = "kanagawa"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending"]

[keys.normal]
"P" = "paste_after"
"p" = "paste_before"
"minus" = ":sh cmake --build build && echo off && fd .exe build > run.bat && run.bat && rm run.bat"
"=" = ":toggle lsp.display-inlay-hints"
"_" = ":sh start ."
"+" = ":sh clang++ main.cpp && echo off && fd .exe > run.bat && run.bat && rm run.bat"

[keys.normal." "]
"P" = "paste_clipboard_after"
"p" = "paste_clipboard_before"
