theme = "kanagawa"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
"P" = "paste_after"
"p" = "paste_before"
"minus" = ":sh cmake --build build && fd .exe build > build.bat && build.bat"
"=" = ":toggle lsp.display-inlay-hints"
"_" = ":sh start ."
"+" = ":sh cargo r"

[keys.normal." "]
"P" = "paste_clipboard_after"
"p" = "paste_clipboard_before"
