New-Item -ItemType Junction -Path "$env:appdata\helix" -Target "$env:userprofile\.win-dotfiles\helix"
New-Item -ItemType Junction -Path "$env:localappdata\nvim" -Target "$env:userprofile\.win-dotfiles\nvim"
New-Item -ItemType SymbolicLink -Path "$env:appdata\Microsoft\Windows\Start Menu\Programs\Startup\remap.ahk" -Target "$env:userprofile\.win-dotfiles\remap.ahk"
New-Item -ItemType SymbolicLink -Path "$env:userprofile\.gitconfig" -Target "$env:userprofile\.win-dotfiles\.gitconfig"
New-Item -ItemType SymbolicLink -Path "$env:userprofile\.wezterm.lua" -Target "$env:userprofile\.win-dotfiles\.wezterm.lua"
