theme = "kanagawa"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending"]

# https://github.com/helix-editor/helix/wiki/Keymap-brainstorm
[keys.normal]
"C-j" = "kill_to_line_start"
"C-k" = "kill_to_line_end"
"A-j" = "delete_word_backward"
"A-k" = "delete_word_forward"
"P" = "paste_after"
"p" = "paste_before"
"F1" = ":sh start ."
"F2" = ":toggle lsp.display-inlay-hints"
"F3" = ":yank-diagnostic"
"F4" = [":format", ":w"]
"F5" = [":w", ":sh taskkill /IM App.exe >nul & cmake --build out/build/x64-Debug -j8 && out\\build\\x64-Debug\\App.exe"]
"minus" = [":w", ":sh taskkill /IM App.exe >nul & cmake --build out/build/x64-Debug -j8 >nul && out\\build\\x64-Debug\\App.exe >nul"]
"=" = ":sh taskkill /F /IM App.exe >nul"

[keys.normal." "]
"P" = "paste_clipboard_after"
"p" = "paste_clipboard_before"
