theme = "kanagawa"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending"]

[keys.normal]
"P" = "paste_after"
"p" = "paste_before"
"F1" = ":sh start ."
"F2" = ":toggle lsp.display-inlay-hints"
"F3" = ":sh emmake make noob -s -j8"
"F4" = ":sh cmake --build build -j8 && start build/game"
"minus" = ":sh make run -s -j8"
"=" = ":sh make kill -s"

[keys.normal." "]
"P" = "paste_clipboard_after"
"p" = "paste_clipboard_before"
