# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations
[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[language-server.clangd]
args = ["--compile-commands-dir=out/build/x64-Debug"]

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
formatter = { command = "goimports" }

[language-server.lobster]
command = "node"
args = ["lobster_lsp.js", "--stdio"]
config = { lobster = { executable = 'lobster.exe', imports = [], experimental = false } }

[[language]]
name = "lobster"
language-servers = ["lobster"]
scope = "source.lobster"
file-types = ["lobster"]
comment-tokens = ["//"]
block-comment-tokens = [{ start = "/*", end = "*/" }]
