[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[language-server.clangd]
args = ["--compile-commands-dir=out/build/x64-Debug"]

[[language]]
name = "cpp"

[[language]]
name = "c"

[[language]]
name = "go"
formatter = { command = "goimports" }

[language-server.lobster]
command = "lobster_lsp"
args = ["--stdio"]

[[language]]
name = "lobster"
language-servers = ["lobster"]
scope = "source.python"
file-types = ["lobster"]
