[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "go"
formatter = { command = "goimports" }
