[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[language-server.clangd]
args = ["--compile-commands-dir=out/build/x64-Debug"]

[[language]]
name = "cpp"

[[language]]
name = "c"

[[language]]
name = "go"
formatter = { command = "goimports" }
